# Series
  - pandas의 기본 객체 중 하나
  - numpy의 ndarray를 기반으로 **인덱싱 기능**이 추가된 **1차원 배열**을 나타냄 (index x value 의 형태)
  - index를 지정하지 않을 시, 기본적으로 ndarray와 같이 0-based 인덱스 생성, 지정할 경우 명시적으로 지정된 index를 사용
  - **같은 타입**의 0개 이상의 데이터를 가질 수 있음

In [1]:
import numpy as np 
import pandas as pd

### Series 
- 실제로 데이터분석, 머신러닝 분야에서 Series 단독으로 사용하는 경우는 없다.
- Series 의 묶음인 DataFrame 에서 파생된 결과로 Series를 사용하는 경우는 있다.
- 실제로 Series 를 생성해서 사용하는 경우 거의 없다.
- 그렇지만 Series 를 이해해야 DataFrame 도 이해가 되기 때문에 배워야 한다.

### Pandas 의 핵심 객체 
> Series : 1차원 데이터 + index   
> DataFrame : 2차원 데이터 + (index, columns)   

## Series 생성 : data로만 생성하기
 - index는 기본적으로 0부터 자동적으로 생성

In [3]:
s1 = pd.Series([1,2,3])
s1

0    1
1    2
2    3
dtype: int64

#### .values .index .dtype

In [4]:
s1.values

array([1, 2, 3], dtype=int64)

In [5]:
type(s1.values)

numpy.ndarray

In [6]:
s1.index

RangeIndex(start=0, stop=3, step=1)

In [7]:
s1.dtype

dtype('int64')

In [8]:
s2 = pd.Series(['a','b','c'])
s2

0    a
1    b
2    c
dtype: object

In [9]:
np.arange(200).dtype

dtype('int32')

In [10]:
s3 = pd.Series(np.arange(200))
s3

0        0
1        1
2        2
3        3
4        4
      ... 
195    195
196    196
197    197
198    198
199    199
Length: 200, dtype: int32

In [11]:
# Series[인덱스] : 값을 반환
s3[4]

4

In [12]:
s1[0]

1

## Series 생성: data, index 함께 명시하여 생성

```
pd.Series(
    data=None,
    index=None,
    dtype:'int',
    name=None,
    copy :
    fastpath ....
)
```

In [13]:
# pd.Series(data , index)
s4 = pd.Series([1,2,3], [100,200,300])
s4

100    1
200    2
300    3
dtype: int64

In [14]:
# Series는 반드시 인덱스명으로 값을 호출 한다.
s4[0]

KeyError: 0

In [15]:
s4[100], s4[200], s4[300]

(1, 2, 3)

In [16]:
s4.index

Index([100, 200, 300], dtype='int64')

In [17]:
# index 반드시 숫자여야 할 이유는 없다.
s5 = pd.Series([1,2,3], ['a','b','c'])
s5

a    1
b    2
c    3
dtype: int64

In [18]:
s5 = pd.Series([1,2,3], ['강호동', '유재석', '신동엽'])
s5

강호동    1
유재석    2
신동엽    3
dtype: int64

In [21]:
s5['강호동'], s5['유재석'], s5['신동엽']

(1, 2, 3)

In [22]:
# index 는 중복값 허용된다.
s6 = pd.Series([1,2,3,4], ['a','b','b','b'])
s6

a    1
b    2
b    3
b    4
dtype: int64

In [23]:
s6['b']

b    2
b    3
b    4
dtype: int64

In [24]:
# index 를 문자열을 사용할 수 있다.
# 하지만 index 이름으로 값을 가져오기 때문에 긴 index 사용하지 않는다.

In [26]:
# index 로 value를 호출한다. 
# dictionary 랑 비슷하다.
# dictionary 사용하면 Series 를 만들 수 있다.
# 키가 index 가 되고 값이 value 가 된다.
dict = {'떡볶이' : '5000원', '김밥' : '3000원', '라면':'5000원'}
s6 = pd.Series(dict)
s6

떡볶이    5000원
김밥     3000원
라면     5000원
dtype: object

##  dtype 명시하여 생성 

In [27]:
s7 = pd.Series(np.arange(5), index=np.arange(100, 105), dtype=np.int16)
s7

100    0
101    1
102    2
103    3
104    4
dtype: int16

In [28]:
# np.arange() : dtype 명시되어 있다.
pd.Series(np.arange(5))

0    0
1    1
2    2
3    3
4    4
dtype: int32

In [29]:
# 명시가 되지 않으면 Pandas 가 자동으로 자료형을 유추한다.
pd.Series([1,2,3])

0    1
1    2
2    3
dtype: int64

In [30]:
pd.Series([1,2,1.3,3.14])

0    1.00
1    2.00
2    1.30
3    3.14
dtype: float64

In [31]:
pd.Series([1,2,1.3,3.14, 'a'])

0       1
1       2
2     1.3
3    3.14
4       a
dtype: object

## 인덱스 활용

In [32]:
s7

100    0
101    1
102    2
103    3
104    4
dtype: int16

In [33]:
s7.index

Index([100, 101, 102, 103, 104], dtype='int32')

In [34]:
s7.index.values

array([100, 101, 102, 103, 104])

In [35]:
s7.values

array([0, 1, 2, 3, 4], dtype=int16)

#### 1.인덱스를 통한 데이터 접근

In [36]:
s7[100]

0

In [37]:
s7[102], s7[103]

(2, 3)

In [38]:
# 결과값은 단일데이터 값 타입

In [39]:
# index 와 값을 같이 출력 - Series 타입
s7[[102]]

102    2
dtype: int16

In [40]:
s7[[102, 104]]

102    2
104    4
dtype: int16

In [41]:
# 인덱스를 명시한 순서대로 출력
s7[[104, 101, 102]]

104    4
101    1
102    2
dtype: int16

In [43]:
# 같은 인덱스를 여러번 호출 가능
s7[[101,101,101,102,102,102,104,104]]

101    1
101    1
101    1
102    2
102    2
102    2
104    4
104    4
dtype: int16

### 2. 인덱스를 통한 데이터 업데이트

In [44]:
s7[104] = 1000

In [45]:
s7

100       0
101       1
102       2
103       3
104    1000
dtype: int16

In [46]:
s7[101] = 102

In [47]:
s7

100       0
101     102
102       2
103       3
104    1000
dtype: int16

In [48]:
# 없는 인덱스 번호에 값을 넣으면 새로 생긴다.
s7[105] = 20000
s7

100        0
101      102
102        2
103        3
104     1000
105    20000
dtype: int16

In [49]:
# 여러 인덱스 값을 한꺼번에 수정 가능
s7[[102,103]] = 101, 103
s7

C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_12556\2740403072.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '(101, 103)' has dtype incompatible with int16, please explicitly cast to a compatible dtype first.
  s7[[102,103]] = 101, 103


100        0
101      102
102      101
103      103
104     1000
105    20000
dtype: int32

### 3. 인덱스 재사용하기

In [50]:
s7.index

Index([100, 101, 102, 103, 104, 105], dtype='int32')

In [51]:
s8 = pd.Series(np.arange(6), s7.index)
s8

100    0
101    1
102    2
103    3
104    4
105    5
dtype: int32

### Series name, Index name, Index 변경

In [52]:
s6

떡볶이    5000원
김밥     3000원
라면     5000원
dtype: object

In [53]:
s6.name = '분식집'

In [54]:
s6

떡볶이    5000원
김밥     3000원
라면     5000원
Name: 분식집, dtype: object

In [55]:
s6.index.name = '메뉴'
s6

메뉴
떡볶이    5000원
김밥     3000원
라면     5000원
Name: 분식집, dtype: object

In [56]:
s6.index = ['김치볶음밥', '오뎅', '만두']
s6

김치볶음밥    5000원
오뎅       3000원
만두       5000원
Name: 분식집, dtype: object