# 1\. 인덱싱 indexing
- 인덱싱은 특정 값을 지정할때 사용한다.
- 파이선 리스트와 동일한 개념으로 사용한다.
- 원소 여러개를 사용할 경우 ,(콤마)를 이용해 각 차원의 인덱스에 접근한다.
- 인덱싱 할 때 마다 차원이 감소한다.


## 1차원 배열 인덱싱

In [4]:
import numpy as np

x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
x[0] # 인덱싱

0

In [6]:
x[9], x[-1] # -1 마지막 인덱스

(9, 9)

In [7]:
x[3] = 200
x

array([  0,   1,   2, 200,   4,   5,   6,   7,   8,   9])

- x는 1차원 배열
- x[0]은 0차원이 된다.
- index의 결과값은 차원이 감소된 결과값이 출력된다.

## 2차원 행렬 인덱싱

In [9]:
x = np.arange(10).reshape(2, 5)
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [10]:
x.shape

(2, 5)

In [11]:
x.ndim

2

In [12]:
x[0]

array([0, 1, 2, 3, 4])

In [13]:
x[1]

array([5, 6, 7, 8, 9])

In [14]:
x[0][2]

2

In [15]:
x[0, 2]

2

In [16]:
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [17]:
x[1, 4], x[1][4], x[1, -1], x[1][-1], x[-1, -1]

(9, 9, 9, 9, 9)

## 3차원 인덱싱

In [19]:
x = np.arange(36).reshape(3,4,3)
x

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]],

       [[24, 25, 26],
        [27, 28, 29],
        [30, 31, 32],
        [33, 34, 35]]])

In [20]:
x[0]

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [21]:
x[0][0]

array([0, 1, 2])

In [22]:
x[0][0][2]

2

In [23]:
x[0,0,2]

2

# 2\. 슬라이싱
- 슬라이싱은 데이터의 범위를 지정할 때 사용한다.
- 리스트, 문자열 slicing 과 동일한 개념으로 사용한다.
- 각 열과 행 구분은 , 로 하며 각 차원별로 슬라이싱이 가능하다.
- 슬라이싱은 차원의 변화가 없다.

## 1차원 슬라이싱

In [24]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
# [시작:끝-1]
x[1:7]

array([1, 2, 3, 4, 5, 6])

In [26]:
# 시작 인덱스 번호가 생략 되면 0 부터 
# 끝 인덱스 번호가 생략 되면 -1 까지
x[1:]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
x[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
# [시작:끝-1:스텝]
x[::2]

array([0, 2, 4, 6, 8])

In [29]:
x[1::3]

array([1, 4, 7])

In [30]:
# 많이 사용하는 방식
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

## 2차원 슬라이싱

In [32]:
x = np.arange(15).reshape(3,5)
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [33]:
x[0]

array([0, 1, 2, 3, 4])

In [34]:
x[1:]

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [35]:
x[::2]

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14]])

In [37]:
x[::2, :3]

array([[ 0,  1,  2],
       [10, 11, 12]])

## 문제.   
위 2차원 배열에서 [[0,1].[5,6]] 만 가져오기



In [39]:
x[:2, :2]

array([[0, 1],
       [5, 6]])

## 3차원 슬라이싱

In [41]:
x = np.arange(54).reshape(2,9,3)
x

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]],

       [[27, 28, 29],
        [30, 31, 32],
        [33, 34, 35],
        [36, 37, 38],
        [39, 40, 41],
        [42, 43, 44],
        [45, 46, 47],
        [48, 49, 50],
        [51, 52, 53]]])

In [46]:
x[:1, :2]

array([[[0, 1, 2],
        [3, 4, 5]]])

In [47]:
x[:1, :2, :]

array([[[0, 1, 2],
        [3, 4, 5]]])

In [48]:
x[0, :2, :]

array([[0, 1, 2],
       [3, 4, 5]])

In [49]:
# numpy 에서 권장하지 않는 방식이다.
x[0][:2][:]

array([[0, 1, 2],
       [3, 4, 5]])

## 문제    
위 내용에서 [[4,5], [31,32]] 를 출력해 보세요.

In [52]:
x[:,1, 1:]

array([[ 4,  5],
       [31, 32]])

## 문제    
다음 결과를 만들어 보세요.
```
[[ 0,  3,  6,  9, 12, 15, 18, 21, 24],
 [27, 30, 33, 36, 39, 42, 45, 48, 51]]
```

In [55]:
x[:, :, 0]

array([[ 0,  3,  6,  9, 12, 15, 18, 21, 24],
       [27, 30, 33, 36, 39, 42, 45, 48, 51]])

## ndarray 는 iterable 하다

In [57]:
arr = np.arange(1, 6)
arr

array([1, 2, 3, 4, 5])

In [58]:
for i in arr:
    print(i)

1
2
3
4
5


In [60]:
arr2 = np.arange(10, 70, 10).reshape(2,3)
arr2

array([[10, 20, 30],
       [40, 50, 60]])

In [62]:
for i in arr2:
    print(i, type(i), i.ndim)

[10 20 30] <class 'numpy.ndarray'> 1
[40 50 60] <class 'numpy.ndarray'> 1


In [63]:
list(arr)

[1, 2, 3, 4, 5]

In [64]:
list(arr2)

[array([10, 20, 30]), array([40, 50, 60])]

앞으로 데이터분석이나, 인공지능에서 다루게 될
수많은 데이터 들이 적게는 3, 4차원에서 많게는 수십 수백차원 데이터도 다룰수 있다. 사실상 3차원 이상의 데이터는 시각화가 거의 불가능 합니다. 머리속으로 차근차근 생각하면서 차원 다루기에 익숙해져야 합니다.