# Broadcasting

#### 브로드캐스팅
  - (기본적으로)Shape이 같은 두 ndarray에 대한 연산은 각 원소별로 진행
  - **다른 Shape을 갖는 array 간 연산** 의 경우 브로드 캐스팅(Shape을 맞춤) 후 진행
    
    
![](https://numpy.org/doc/stable/_images/broadcasting_1.png)

#### 브로드캐스팅 Rule
 - [Rule 공식문서](https://docs.scipy.org/doc/numpy/user/basics.broadcasting.html#general-broadcasting-rules)
 - 뒷 차원에서 부터 비교하여 **①Shape이 같거나**, **②차원 중 값이 1인 것이 존재**하면 가능
 - 결과 차원은 둘중 큰 size 의 차원으로 **확장(stretch)** 된다

![브로드캐스팅 예](https://www.tutorialspoint.com/numpy/images/array.jpg)
    - 출처: https://www.tutorialspoint.com/numpy/images/array.jpg

- Broadcatding 의 강점은 shape 가 다른 데이터 까지의 연산을 '특별한 처리' 없이도 연산이 가능케 한다.

## Shape 이 같은 연산

In [1]:
import numpy as np 
x = np.arange(15).reshape(3, 5)
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [2]:
y = np.arange(15).reshape(3, 5)
y

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [3]:
x.shape, y.shape

((3, 5), (3, 5))

In [4]:
np.add(x, y)

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

In [5]:
x + y

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

In [6]:
np.subtract(x, y)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [7]:
x - y

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [8]:
np.multiply(x, y)

array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196]])

In [9]:
x * y

array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196]])

In [10]:
np.divide(x, y)

C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_1224\3068331862.py:1: RuntimeWarning: invalid value encountered in divide
  np.divide(x, y)


array([[nan,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [12]:
x / y

C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_1224\3016948717.py:1: RuntimeWarning: invalid value encountered in divide
  x / y


array([[nan,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

## Shape이 다른 경우 연산

In [13]:
a = np.arange(12).reshape(4,3)
b = np.arange(100, 103)
a, b

(array([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]]),
 array([100, 101, 102]))

In [14]:
a.shape, b.shape

((4, 3), (3,))

In [15]:
a + b

array([[100, 102, 104],
       [103, 105, 107],
       [106, 108, 110],
       [109, 111, 113]])

In [17]:
c = np.arange(1000, 1004)
c, c.shape

(array([1000, 1001, 1002, 1003]), (4,))

In [18]:
a + c

ValueError: operands could not be broadcast together with shapes (4,3) (4,) 

- 행렬의 수가 다르면 에러가 발생한다.

In [19]:
d = b.reshape(1,3)

In [20]:
d.shape

(1, 3)

In [21]:
a + d

array([[100, 102, 104],
       [103, 105, 107],
       [106, 108, 110],
       [109, 111, 113]])

In [23]:
d = np.arange(6).reshape(2,3)

In [24]:
d.shape

(2, 3)

In [25]:
a + d

ValueError: operands could not be broadcast together with shapes (4,3) (2,3) 

- 열이 같다고 하더라도 행의 수가 하나이거나 같아야 한다.

In [26]:
e = np.array([[[[10]]]])
e.shape

(1, 1, 1, 1)

In [27]:
a + e

array([[[[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18],
         [19, 20, 21]]]])

## 문제.   
위 두개의 array를 더하여 아래와 같은 결과를 만들어 보세요.
```
array([[11,22,31], [42,51,62]])
```

In [29]:
arr21 = np.arange(10, 70, 10).reshape(2, 3)
arr23 = np.array([1,2])

In [30]:
arr21, arr23

(array([[10, 20, 30],
        [40, 50, 60]]),
 array([1, 2]))

In [31]:
arr21 + arr23

ValueError: operands could not be broadcast together with shapes (2,3) (2,) 

In [32]:
arr21.reshape(3,2) + arr23

array([[11, 22],
       [31, 42],
       [51, 62]])

In [33]:
(arr21.reshape(3,2) + arr23).reshape(2,3)

array([[11, 22, 31],
       [42, 51, 62]])

In [41]:
arr23.reshape(2,1)

array([[1],
       [2]])

### Broadcating 조건
1. shape 이 완전히 다 같아야 한다.    
2. 열의 수가 같아야 한다.    
3. 열의 값이 하나 일때 가능하다.    
4. 대입되는 array의 행이 하나 일때 연산되는 array의 행이 많다 하더라도 각 행의 열의 값이 하나 일 때


## Broadcasting Rule
- [Rule 공식문서](https://docs.scipy.org/doc/numpy/user/basics.broadcasting.html#general-broadcasting-rules)
 - 뒷 차원에서 부터 비교하여 **①Shape이 같거나**, **②차원 중 값이 1인 것이 존재**하면 가능
 - 결과 차원은 둘중 큰 size 의 차원으로 **확장(stretch)** 된다

![브로드캐스팅 예](https://www.tutorialspoint.com/numpy/images/array.jpg)
    - 출처: https://www.tutorialspoint.com/numpy/images/array.jpg

```
    브로드캐스팅 가용한 경우
    
    A     : 256 x 256 x 3
    B     :             3
    Result: 256 x 256 x 3   <-- 결과 차원은 둘중 큰 size의 차원으로 확장

    A     : 8 x 1 x 6 x 1
    B     :     7 x 1 x 5
    Result: 8 x 7 x 6 x 5       
```

In [43]:
a = np.full(4, 100)
a

array([100, 100, 100, 100])

In [44]:
a + 1

array([101, 101, 101, 101])

In [45]:
a + [1]

array([101, 101, 101, 101])

In [46]:
a + [[1]]

array([[101, 101, 101, 101]])

In [47]:
a + [[[1]]]

array([[[101, 101, 101, 101]]])

In [48]:
a + [1,2,3,4]

array([101, 102, 103, 104])

In [49]:
# 행의 수는 동일하지만 열의 수가 달라서 에러가 발생한다.
a + [1, 3]

ValueError: operands could not be broadcast together with shapes (4,) (2,) 

In [51]:
b = np.arange(1, 9).reshape(2,4)
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [52]:
a + b

array([[101, 102, 103, 104],
       [105, 106, 107, 108]])

In [53]:
b = np.arange(1,3).reshape(2,1)
b

array([[1],
       [2]])

In [54]:
a + b

array([[101, 101, 101, 101],
       [102, 102, 102, 102]])

In [56]:
b = np.arange(6).reshape(2,3,1)
b

array([[[0],
        [1],
        [2]],

       [[3],
        [4],
        [5]]])

In [57]:
a + b

array([[[100, 100, 100, 100],
        [101, 101, 101, 101],
        [102, 102, 102, 102]],

       [[103, 103, 103, 103],
        [104, 104, 104, 104],
        [105, 105, 105, 105]]])

In [60]:
a = np.full(8, 100).reshape(2,4)
a

array([[100, 100, 100, 100],
       [100, 100, 100, 100]])

In [61]:
a + b

ValueError: operands could not be broadcast together with shapes (2,4) (2,3,1) 