# Broadcasting

#### 브로드캐스팅
  - (기본적으로)Shape이 같은 두 ndarray에 대한 연산은 각 원소별로 진행
  - **다른 Shape을 갖는 array 간 연산** 의 경우 브로드 캐스팅(Shape을 맞춤) 후 진행
    
    
![](https://numpy.org/doc/stable/_images/broadcasting_1.png)

#### 브로드캐스팅 Rule
 - [Rule 공식문서](https://docs.scipy.org/doc/numpy/user/basics.broadcasting.html#general-broadcasting-rules)
 - 뒷 차원에서 부터 비교하여 **①Shape이 같거나**, **②차원 중 값이 1인 것이 존재**하면 가능
 - 결과 차원은 둘중 큰 size 의 차원으로 **확장(stretch)** 된다

![브로드캐스팅 예](https://www.tutorialspoint.com/numpy/images/array.jpg)
    - 출처: https://www.tutorialspoint.com/numpy/images/array.jpg

- Broadcatding 의 강점은 shape 가 다른 데이터 까지의 연산을 '특별한 처리' 없이도 연산이 가능케 한다.

## Shape 이 같은 연산

## Shape이 다른 경우 연산

- 행렬의 수가 다르면 에러가 발생한다.

- 열이 같다고 하더라도 행의 수가 하나이거나 같아야 한다.

## 문제.   
위 두개의 array를 더하여 아래와 같은 결과를 만들어 보세요.
```
array([[11,22,31], [42,51,62]])
```

In [4]:
import numpy as np
arr21 = np.arange(10, 70, 10).reshape(2,3)
print(arr21)
arr23 = np.array([1,2])
print(arr23)

[[10 20 30]
 [40 50 60]]
[1 2]


In [26]:
(arr21.reshape(3,2) + arr23).reshape(2,3)

array([[11, 22, 31],
       [42, 51, 62]])

## Broadcasting Rule
- [Rule 공식문서](https://docs.scipy.org/doc/numpy/user/basics.broadcasting.html#general-broadcasting-rules)
 - 뒷 차원에서 부터 비교하여 **①Shape이 같거나**, **②차원 중 값이 1인 것이 존재**하면 가능
 - 결과 차원은 둘중 큰 size 의 차원으로 **확장(stretch)** 된다

![브로드캐스팅 예](https://www.tutorialspoint.com/numpy/images/array.jpg)
    - 출처: https://www.tutorialspoint.com/numpy/images/array.jpg

```
    브로드캐스팅 가용한 경우
    
    A     : 256 x 256 x 3
    B     :             3
    Result: 256 x 256 x 3   <-- 결과 차원은 둘중 큰 size의 차원으로 확장

    A     : 8 x 1 x 6 x 1
    B     :     7 x 1 x 5
    Result: 8 x 7 x 6 x 5       
```

In [35]:
a = np.full(4, 100)
a


array([100, 100, 100, 100])

In [34]:
b = np.arange(1,9).reshape(2,4)
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [30]:
a + b

array([[101, 102, 103, 104],
       [105, 106, 107, 108]])

In [31]:
b = np.arange(1,3).reshape(2,1)
b

array([[1],
       [2]])

In [32]:
a + b

array([[101, 101, 101, 101],
       [102, 102, 102, 102]])

In [36]:
b = np.arange(6).reshape(2,3,1)
b

array([[[0],
        [1],
        [2]],

       [[3],
        [4],
        [5]]])

In [37]:
a + b

array([[[100, 100, 100, 100],
        [101, 101, 101, 101],
        [102, 102, 102, 102]],

       [[103, 103, 103, 103],
        [104, 104, 104, 104],
        [105, 105, 105, 105]]])

In [38]:
a= np.full(8, 100).reshape(2,4)
a

array([[100, 100, 100, 100],
       [100, 100, 100, 100]])

In [39]:
a + b

ValueError: operands could not be broadcast together with shapes (2,4) (2,3,1) 