# Boolean indexing

- 중요! 'Boolean indexing ' !
- ndarray 인덱싱 시, bool 리스트를 전달하여 True인 경우만 필터링

- for 사용하지 않고도 ndarray 에서 '조건'에 맞는 데이터만 추출 하는 기능

- 머신러닝 등에 있어서도 많이 사용

- 브로드캐스팅을 활용하여 ndarray로 부터 bool list 얻기
- 예) 짝수인 경우만 찾아보기

In [1]:
import numpy as np

np.random.seed(10)
x = np.random.randint(1, 100, size=10)
x

array([10, 16, 65, 29, 90, 94, 30,  9, 74,  1])

In [4]:
evenMask = x % 2

In [5]:
print(x)
print(evenMask)

[10 16 65 29 90 94 30  9 74  1]
[0 0 1 1 0 0 0 1 0 1]


In [11]:
x[evenMask == 0]

array([10, 16, 90, 94, 30, 74])

- 위와 같이 Boolean indexing 된 array를 Mask라고도 한다.

## Boolean mask 를 인덱스로 전달

- 인덱스에 boolean mask를 넣어보면 짝수만 필터링 되어 나온다.

- boolean mask 로서 list, tuple을 넣어줘도 필터 동작은 가능하다.

- 보통은 한번에 작성하여 사용한다.

## 문제.   
x 에서 30보다 큰 수만 출력해보세요.

In [12]:
x[x > 30]

array([65, 90, 94, 74])

## 다중 조건 사용하기
- 파이썬 논리 연산자인 and, or, not 키워드는 사용 불가
- & ← AND
- | ← OR

In [14]:
x[(x % 2 == 0) & (x > 30)]

array([90, 94, 74])

## astype(int)로 변환

- 머신러닝 등 데이터 분석시 onehot encoding으로 변환할 때 많이 사용된다.
- onehot encoding 은 문자열을 정수 데이터로 변경하는 것을 말한다.

In [17]:
((x % 2 == 0) & (x > 30)).astype(int)

array([0, 0, 0, 0, 1, 1, 0, 0, 1, 0])

In [18]:
((x % 2 == 0) & (x > 30)).sum()

3